apiVersion: apps/v1
kind: Deployment
metadata:
  name: collection
  namespace: lakehouse-track
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: vector
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi
        - name: meta-api
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
