apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: starrocks-cn
  namespace: lakehouse-track
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: cn
          resources:
            requests:
              cpu: "500m"
              memory: 2Gi
            limits:
              cpu: "2"
              memory: 4Gi
  volumeClaimTemplates:
    - metadata:
        name: cn-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
    - metadata:
        name: cn-datacache
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
