# Kind 单节点实验室集群（本机 Docker）
# 宿主机端口避开现有 DataSage MinIO(:9000) / 其它占用
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: lakehouse
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30903
        hostPort: 9030
        protocol: TCP
      - containerPort: 30080
        hostPort: 18080
        protocol: TCP
      - containerPort: 30900
        hostPort: 19000
        protocol: TCP
      - containerPort: 30901
        hostPort: 19001
        protocol: TCP
