-- ============================================================
-- 埋点元数据表：全部在 schema stellar_trace（默认库 postgres）
-- 库：postgres（默认）| metastore（仅 Hive，见 03）
--
-- ⚠️ 警告：此脚本包含 DROP TABLE，仅由 PostgreSQL initdb 在空数据卷时自动执行。
-- 切勿对已有数据的环境手动执行，否则会丢失所有业务数据！
-- ============================================================
CREATE SCHEMA IF NOT EXISTS stellar_trace;
SET search_path TO stellar_trace;
DROP TABLE IF EXISTS track_event_property;
DROP TABLE IF EXISTS track_event_define;
DROP TABLE IF EXISTS track_property_define;
DROP TABLE IF EXISTS track_project;

-- ---------- 项目表 ----------
CREATE TABLE track_project (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name            VARCHAR(100)  NOT NULL,           -- 项目英文标识，全局唯一
  cname           VARCHAR(255),                     -- 项目中文名称
  super_token     VARCHAR(255),                     -- 超级令牌（管理接口鉴权）
  normal_token    VARCHAR(255),                     -- 普通令牌（数据上报鉴权）
  is_auto_create  SMALLINT      DEFAULT 1,          -- 是否自动创建：1=是 0=否
  status          INTEGER       NOT NULL,           -- 项目状态：1=正常 0=停用
  delete_time     TIMESTAMP,                        -- 软删除时间
  create_time     TIMESTAMP                         -- 创建时间
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_track_project_name
  ON track_project(name);

COMMENT ON TABLE track_project IS '埋点项目';

-- ---------- 事件定义表 ----------
CREATE TABLE track_event_define (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id      INTEGER       DEFAULT NULL,       -- 所属项目 ID；NULL=公共预置
  name            VARCHAR(100)  NOT NULL,           -- 事件英文标识，如 $AppStart
  cname           VARCHAR(100),                     -- 事件中文名称
  visible         SMALLINT      DEFAULT 1,          -- 是否在界面可见：1=可见 0=隐藏
  virtual         SMALLINT      DEFAULT 0,          -- 是否虚拟事件：1=是 0=否
  bucket_id       INTEGER,                          -- 存储桶 ID
  is_visualized   SMALLINT      DEFAULT 0,          -- 是否可视化圈选创建：1=是
  virtual_define  TEXT,                             -- 虚拟事件定义（JSON）
  accepted        SMALLINT      DEFAULT 1,          -- 是否入库：1=接收 0=丢弃
  total_count     BIGINT        DEFAULT 0,          -- 累计触发次数
  track_info      TEXT,                             -- 采集信息（JSON：sdks/auto/category 等）
  comment         TEXT,                             -- 事件说明（触发条件/业务含义）
  user_id         INTEGER,                          -- 创建人 ID
  is_common       SMALLINT      DEFAULT 0,          -- 是否公共预置：1=预置 0=项目自定义
  update_time     TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP,
  create_time     TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_track_event_define_project_name
  ON track_event_define(project_id, name) WHERE project_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_track_event_define_common_name
  ON track_event_define(name) WHERE project_id IS NULL;

COMMENT ON TABLE track_event_define IS '事件定义（预置 + 自定义）';

-- ---------- 属性定义表 ----------
CREATE TABLE track_property_define (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id       INTEGER       DEFAULT NULL,       -- 所属项目 ID；NULL=公共预置
  name             VARCHAR(100)  NOT NULL,           -- 属性英文标识，如 $os
  cname            VARCHAR(100),                     -- 属性中文名称
  unit             VARCHAR(16),                      -- 度量单位：秒/像素/天/小时/分钟/KB 等
  data_type        INTEGER       NOT NULL,           -- 数据类型：1=整数 2=字符串 3=浮点/列表 5=日期时间 6=布尔
  comment          TEXT,                             -- 属性说明（含义/采集细节/注意事项）
  is_common        SMALLINT      DEFAULT 0,          -- 是否公共预置：1=预置 0=项目自定义
  is_dimension     SMALLINT,                         -- 是否分析维度：1=维度 0=否
  is_measure       SMALLINT,                         -- 是否度量指标：1=指标 0=否
  is_in_use        SMALLINT      DEFAULT 1,          -- 是否启用：1=启用 0=停用
  is_load          SMALLINT      DEFAULT 1,          -- 是否加载到查询引擎：1=是
  has_dict         SMALLINT      DEFAULT 0,          -- 是否有字典：1=有
  default_value    VARCHAR(1024),                    -- 默认值
  type_flexible    INTEGER       DEFAULT 1,          -- 类型是否可变：1=可变
  track_info       TEXT,                             -- 采集信息（JSON：sdks/source/category/privacy 等）
  view_column_name VARCHAR(128),                     -- 查询引擎列名，如 p__os
  update_time      TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP,
  create_time      TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_track_property_define_project_name
  ON track_property_define(name, project_id) WHERE project_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_track_property_define_common_name
  ON track_property_define(name) WHERE project_id IS NULL;

COMMENT ON TABLE track_property_define IS '属性定义（预置 + 自定义）';

-- ---------- 事件-属性关联表 ----------
CREATE TABLE track_event_property (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id    INTEGER      NOT NULL,                -- 关联事件 ID
  property_id INTEGER      NOT NULL,                -- 关联属性 ID
  update_time TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_track_event_property_unique
  ON track_event_property(event_id, property_id);

COMMENT ON TABLE track_event_property IS '事件与属性的多对多关联';

-- ---------- 用户 ID 映射表 ----------
CREATE TABLE track_user_id_mapping (
  project_name VARCHAR(100) NOT NULL,               -- 所属项目标识
  distinct_id  VARCHAR(256) NOT NULL,               -- 匿名 ID / 设备 ID
  map_id       VARCHAR(256) NOT NULL,               -- 映射目标 ID（登录 ID）
  map_type     VARCHAR(100) NOT NULL,               -- 映射类型
  login_id     VARCHAR(256),                        -- 登录 ID
  load_time    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (project_name, distinct_id)
);

COMMENT ON TABLE track_user_id_mapping IS '用户 ID 关联映射（匿名↔登录）';

-- ============================================================
-- 预置事件/属性：放入正式表，通过 is_common 区分
--   project_id IS NULL AND is_common = 1  → 公共预置，所有项目共享
--   project_id = ?  AND is_common = 0     → 项目私有业务事件/属性
--
-- 查询某项目全量事件：WHERE project_id = ? OR (project_id IS NULL AND is_common = 1)
-- ============================================================

-- 预置事件（38 个，project_id=NULL, is_common=1）
INSERT INTO track_event_define (project_id, name, cname, is_common, comment, track_info) VALUES
  (NULL, '$ABTestTrigger', 'A/B 测试命中', 1, '命中实验时触发，携带实验 ID 和实验组 ID', '{"sdks":["Web","App"],"auto":true}'),
  (NULL, '$AppChannelMatching', '访问渠道追踪链接', 1, '用户访问渠道追踪链接时触发，用于 App 渠道归因', '{"sdks":["iOS","Android"],"auto":true,"category":"Channel"}'),
  (NULL, '$AppClick', 'App 元素点击', 1, '点击 App 控件时触发（全埋点），采集元素 ID/内容/类型/位置等', '{"sdks":["iOS","Android"],"auto":true,"category":"AutoTrack"}'),
  (NULL, '$AppEnd', 'App 退出', 1, 'Android: 退到后台或关闭 App 等待 30 秒触发; iOS: 退出或进入后台时触发; 主要属性: $event_duration', '{"sdks":["iOS","Android","HarmonyOS"],"auto":true}'),
  (NULL, '$AppInstall', 'App 安装后首次启动', 1, '调用 trackAppInstall 接口采集，仅安装后首次启动触发一次，用于渠道归因', '{"sdks":["iOS","Android"],"auto":false}'),
  (NULL, '$AppPageLeave', 'App 页面离开', 1, 'App 页面离开时触发，携带页面浏览时长 $event_duration', '{"sdks":["iOS","Android"],"auto":true}'),
  (NULL, '$AppRemoteConfigChanged', '远程控制配置变化', 1, 'SDK 获取远程配置并加载生效后触发，携带 $app_remote_config', '{"sdks":["iOS","Android"],"auto":true}'),
  (NULL, '$AppStart', 'App 启动', 1, '启动 App 或从后台切换到前台时触发; 主要属性: $is_first_time, $resume_from_background', '{"sdks":["iOS","Android","HarmonyOS"],"auto":true}'),
  (NULL, '$AppStartPassively', 'App 被动启动', 1, 'iOS 后台被动启动（如后台刷新）时触发，独有属性 $app_state', '{"sdks":["iOS"],"auto":true}'),
  (NULL, '$AppViewScreen', 'App 浏览页面', 1, '打开页面时触发（Android: Activity/Fragment; iOS: ViewController）', '{"sdks":["iOS","Android"],"auto":true,"category":"AutoTrack"}'),
  (NULL, '$ChannelLinkReaching', '渠道链接到达', 1, '用户点击渠道链接到达落地页时触发，采集渠道关键词 ID 等', '{"sdks":["Web"],"auto":true,"category":"Channel"}'),
  (NULL, '$MPAddFavorites', '小程序收藏', 1, '用户收藏小程序时触发', '{"sdks":["MiniProgram"],"auto":true}'),
  (NULL, '$MPHide', '小程序进入后台', 1, '小程序从前台进入后台时触发（onHide 生命周期），携带停留时长 $event_duration', '{"sdks":["MiniProgram"],"auto":true,"lifecycle":"App.onHide"}'),
  (NULL, '$MPLaunch', '小程序启动', 1, '小程序初始化完成或被杀死后重新打开时全局触发一次（App.onLaunch），携带 $scene 启动场景', '{"sdks":["MiniProgram"],"auto":true,"lifecycle":"App.onLaunch"}'),
  (NULL, '$MPShare', '小程序分享', 1, '用户分享小程序时触发，采集分享途径和路径', '{"sdks":["MiniProgram"],"auto":true}'),
  (NULL, '$MPShow', '小程序显示', 1, '小程序启动或从后台切换到前台时触发（App.onShow），携带 $scene', '{"sdks":["MiniProgram"],"auto":true,"lifecycle":"App.onShow"}'),
  (NULL, '$MPViewScreen', '小程序页面浏览', 1, '打开小程序页面时触发，采集页面路径和参数', '{"sdks":["MiniProgram"],"auto":true}'),
  (NULL, '$PlanConverted', '已转化完成', 1, '智能运营计划中用户完成转化目标时触发', '{"sdks":["Server"],"auto":true,"category":"Operation"}'),
  (NULL, '$PlanMsgArrived', '消息同步终态信息', 1, '运营计划消息到达终态（成功/失败）时触发', '{"sdks":["Server"],"auto":true,"category":"Operation"}'),
  (NULL, '$PlanMsgSendDone', '消息已发出', 1, '运营计划消息发送完成时触发', '{"sdks":["Server"],"auto":true,"category":"Operation"}'),
  (NULL, '$PlanMsgSendPrepare', '消息准备发出', 1, '运营计划消息准备发送时触发', '{"sdks":["Server"],"auto":true,"category":"Operation"}'),
  (NULL, '$PlanPopupClick', '弹窗点击', 1, '用户点击弹窗按钮时触发，采集按钮类型/文案/行为', '{"sdks":["Web","App"],"auto":true,"category":"Operation"}'),
  (NULL, '$PlanPopupDisplay', '弹窗展示', 1, '弹窗展示时触发，采集计划 ID/消息 ID/平台标签等', '{"sdks":["Web","App"],"auto":true,"category":"Operation"}'),
  (NULL, '$ShortUrlRedirect', '短链跳转', 1, '用户通过短链跳转时触发', '{"sdks":["Server"],"auto":true,"category":"Channel"}'),
  (NULL, '$SignUp', '关联 ID', 1, '用户登录时触发，用于关联匿名 ID 和登录 ID，携带 $track_signup_original_id', '{"sdks":["iOS","Android","Web","MiniProgram","Server"],"auto":false}'),
  (NULL, '$WebClick', 'Web 元素点击', 1, '点击页面元素时自动触发（全埋点），采集元素 ID/内容/类型/选择器/位置等', '{"sdks":["Web"],"auto":true,"category":"AutoTrack"}'),
  (NULL, '$WebPageLeave', 'Web 页面离开', 1, '页面失焦/切换/关闭/跳转时触发，$event_duration 为页面浏览时长（秒）', '{"sdks":["Web"],"auto":true}'),
  (NULL, '$WebPageLoad', 'Web 页面加载', 1, '基于 Performance API 计算页面加载时间，$event_duration 为加载时长（秒），$page_resource_size 为资源大小（KB）', '{"sdks":["Web"],"auto":true}'),
  (NULL, '$WebStay', 'Web 视区停留', 1, '页面有效停留超过 4 秒并滚动时触发，用于可达性热力图', '{"sdks":["Web"],"auto":true,"category":"AutoTrack"}'),
  (NULL, '$WechatClickMenu', '点击微信公众号菜单', 1, '用户点击微信公众号自定义菜单时触发', '{"sdks":["Server"],"auto":true,"category":"WeChat"}'),
  (NULL, '$WechatClickMsgmenu', '点击微信菜单会话', 1, '用户点击微信公众号菜单会话消息选项时触发', '{"sdks":["Server"],"auto":true,"category":"WeChat"}'),
  (NULL, '$WechatFollow', '关注微信公众号', 1, '用户关注微信公众号时触发', '{"sdks":["Server"],"auto":true,"category":"WeChat"}'),
  (NULL, '$WechatReceiveMsgFromUser', '微信公众号接收用户消息', 1, '微信公众号收到用户发送的消息时触发', '{"sdks":["Server"],"auto":true,"category":"WeChat"}'),
  (NULL, '$WechatScanQrcodeScene', '扫描微信参数二维码', 1, '用户扫描带参数的微信二维码时触发', '{"sdks":["Server"],"auto":true,"category":"WeChat"}'),
  (NULL, '$WechatServiceMsgSendDone', '微信客服消息终态信息', 1, '微信客服消息发送达到终态时触发', '{"sdks":["Server"],"auto":true,"category":"WeChat"}'),
  (NULL, '$WechatUnfollow', '取关微信公众号', 1, '用户取消关注微信公众号时触发', '{"sdks":["Server"],"auto":true,"category":"WeChat"}'),
  (NULL, '$WechatUpdateUserLocation', '上报微信用户地理位置', 1, '微信用户授权地理位置后定期上报时触发', '{"sdks":["Server"],"auto":true,"category":"WeChat"}'),
  (NULL, '$pageview', 'Web 浏览页面', 1, '打开页面时自动触发（autoTrack），采集 URL/标题/前向地址/UTM 参数等', '{"sdks":["Web"],"auto":true,"category":"AutoTrack"}');

-- 预置属性（199 个，project_id=NULL, is_common=1）
-- data_type: 1=整数  2=字符串  3=浮点/列表  5=日期时间  6=布尔
-- track_info: JSON（sdks/source/category/privacy/auto/note 等）
INSERT INTO track_property_define
  (project_id, name, cname, data_type, unit, view_column_name, is_common, comment, track_info, is_dimension, is_measure)
SELECT NULL, name, cname, data_type, unit, 'p__'||REPLACE(name,'$',''), 1, comment, track_info, is_dimension, is_measure
FROM (VALUES
  ('$abtest_experiment_group_id', '实验组 ID', 2, NULL, 'A/B 测试实验组 ID', '{"sdks":["Web","App"],"category":"ABTest"}', 1, 0),
  ('$abtest_experiment_id', '实验 ID', 2, NULL, 'A/B 测试实验 ID', '{"sdks":["Web","App"],"category":"ABTest"}', 1, 0),
  ('$app_crashed_reason', '崩溃原因', 2, NULL, 'App 崩溃时的调用栈信息', '{"sdks":["iOS","Android"],"auto":true,"category":"Basic"}', 0, 0),
  ('$app_id', '应用唯一标识', 2, NULL, '应用的唯一标识符，Android/iOS/小程序均采集', '{"sdks":["iOS","Android","MiniProgram"],"auto":true,"category":"Basic"}', 1, 0),
  ('$app_name', '应用名称', 2, NULL, '应用名称', '{"sdks":["iOS","Android"],"auto":true,"category":"Basic"}', 1, 0),
  ('$app_remote_config', '远程控制配置信息', 2, NULL, 'SDK 远程配置加载生效时的配置内容', '{"sdks":["iOS","Android"],"auto":true,"category":"Basic"}', 0, 0),
  ('$app_state', 'App 状态', 2, NULL, 'App 当前状态，仅在 $AppStartPassively 事件中可用', '{"sdks":["iOS"],"auto":true,"category":"Basic"}', 1, 0),
  ('$app_type_info', '应用/公众号类型', 2, NULL, '应用或公众号类型信息', '{"sdks":["Server"],"category":"WeChat"}', 1, 0),
  ('$app_version', '应用版本', 2, NULL, 'App 应用版本号', '{"sdks":["iOS","Android"],"auto":true,"category":"Basic","privacy":"Low"}', 1, 0),
  ('$bot_name', '爬虫名称', 2, NULL, 'SDK 识别到爬虫访问时尝试解析的爬虫名称', '{"sdks":["Web"],"auto":true,"category":"Basic","privacy":"Low"}', 1, 0),
  ('$brand', '设备品牌', 2, NULL, '设备品牌，仅 Android 采集', '{"sdks":["iOS","Android"],"auto":true,"category":"Device","privacy":"Medium"}', 1, 0),
  ('$browser', '浏览器', 2, NULL, '浏览器名称，从 UserAgent 解析', '{"sdks":["Web"],"auto":true,"source":"UA","category":"Browser","privacy":"Medium"}', 1, 0),
  ('$browser_language', '用户浏览器语言', 2, NULL, '浏览器语言设置', '{"sdks":["Web"],"auto":true,"category":"Browser"}', 1, 0),
  ('$browser_version', '浏览器版本', 2, NULL, '浏览器版本号，从 UserAgent 解析', '{"sdks":["Web"],"auto":true,"source":"UA","category":"Browser","privacy":"Medium"}', 1, 0),
  ('$carrier', '运营商', 2, NULL, '设备 SIM 卡运营商；iOS 16.4+ 后无法采集', '{"sdks":["iOS","Android"],"auto":true,"category":"Device","privacy":"Medium","note":"iOS 16.4+不可用"}', 1, 0),
  ('$channel_account_id', '渠道广告主 ID', 2, NULL, '渠道广告主 ID', '{"sdks":["iOS","Android"],"category":"Channel"}', 1, 0),
  ('$channel_active_period_day', '有效激活窗口期（天）', 1, '天', '记录激活窗口期配置信息，可追溯窗口期变更导致的激活变化', '{"sdks":["iOS","Android"],"category":"Channel"}', 1, 0),
  ('$channel_active_result', '渠道有效激活标识', 6, NULL, '渠道激活是否有效', '{"sdks":["iOS","Android"],"category":"Channel"}', 1, 0),
  ('$channel_ad_id', '渠道广告创意 ID', 2, NULL, '渠道广告创意 ID', '{"sdks":["iOS","Android"],"category":"Channel"}', 1, 0),
  ('$channel_adgroup_id', '渠道广告组 ID', 2, NULL, '渠道广告组 ID', '{"sdks":["iOS","Android"],"category":"Channel"}', 1, 0),
  ('$channel_attribute_period_hour', '激活归因窗口期（小时）', 1, '小时', '激活归因窗口期', '{"sdks":["iOS","Android"],"category":"Channel"}', 1, 0),
  ('$channel_callback_period_day', '深度回传归因窗口（天）', 1, '天', '深度回传归因窗口期', '{"sdks":["iOS","Android"],"category":"Channel"}', 1, 0),
  ('$channel_campaign_id', '渠道广告计划 ID', 2, NULL, '渠道广告计划 ID', '{"sdks":["iOS","Android"],"category":"Channel"}', 1, 0),
  ('$channel_click_id', '渠道点击 ID', 2, NULL, '渠道点击 ID，用于与广告平台核对点击数据', '{"sdks":["iOS","Android"],"category":"Channel"}', 1, 0),
  ('$channel_device_info', '渠道设备指纹信息', 2, NULL, 'App 渠道匹配所需的设备指纹信息，入库后删除', '{"sdks":["iOS","Android"],"category":"Channel","privacy":"High","note":"不入库"}', 0, 0),
  ('$channel_extra_information', '渠道额外信息', 2, NULL, '渠道追踪链接中附加的额外信息（如 IMEI、OAID）', '{"sdks":["iOS","Android"],"category":"Channel","privacy":"High"}', 0, 0),
  ('$channel_keyword_id', '渠道关键词 ID', 2, NULL, '渠道关键词 ID', '{"sdks":["Web"],"category":"Channel"}', 1, 0),
  ('$channel_name', '渠道名称', 2, NULL, '渠道名称，关联前端投放数据，用于生成投放分析报告', '{"sdks":["iOS","Android"],"category":"Channel"}', 1, 0),
  ('$city', '城市', 2, NULL, '由 IP 解析得到', '{"sdks":["iOS","Android","Web","MiniProgram","Server"],"source":"IP","auto":true,"category":"IP","privacy":"Low"}', 1, 0),
  ('$country', '国家', 2, NULL, '由 IP 解析得到', '{"sdks":["iOS","Android","Web","MiniProgram","Server"],"source":"IP","auto":true,"category":"IP","privacy":"Low"}', 1, 0),
  ('$create_time', '创建时间', 1, NULL, '记录创建时间', '{"category":"Basic"}', 0, 0),
  ('$device_id', '设备 ID', 2, NULL, 'Android: AndroidID; iOS: IDFA 或 IDFV', '{"sdks":["iOS","Android"],"auto":true,"category":"Device","privacy":"High"}', 1, 0),
  ('$device_id_list', '关联设备 ID', 3, NULL, '关联的设备 ID 列表', '{"sdks":["iOS","Android"],"category":"Device"}', 0, 0),
  ('$device_type', '关联设备类型', 2, NULL, '关联设备的类型', '{"sdks":["iOS","Android"],"category":"Device"}', 1, 0),
  ('$element_class_name', '元素样式名', 2, NULL, '元素 class 属性', '{"sdks":["Web","iOS","Android"],"auto":true,"category":"Click"}', 0, 0),
  ('$element_content', '元素内容', 2, NULL, '元素标签之间的直接文本内容', '{"sdks":["Web","iOS","Android","MiniProgram"],"auto":true,"category":"Click"}', 0, 0),
  ('$element_id', '元素 ID', 2, NULL, 'Android: Widget android:id; Web: 元素 id 属性', '{"sdks":["Web","iOS","Android","MiniProgram"],"auto":true,"category":"Click"}', 0, 0),
  ('$element_name', '元素名称', 2, NULL, '元素 name 属性', '{"sdks":["Web","iOS","Android","MiniProgram"],"auto":true,"category":"Click"}', 0, 0),
  ('$element_path', '元素路径', 2, NULL, '元素 DOM 路径信息，用于热力图匹配', '{"sdks":["Web","iOS","Android"],"auto":true,"category":"Click"}', 0, 0),
  ('$element_position', '元素位置', 2, NULL, '列表控件中被点击元素的位置索引', '{"sdks":["Web","iOS","Android","MiniProgram"],"auto":true,"category":"Click"}', 0, 0),
  ('$element_selector', '元素选择器', 2, NULL, '元素 CSS 选择器', '{"sdks":["Web"],"auto":true,"category":"Click"}', 0, 0),
  ('$element_target_url', '元素链接地址', 2, NULL, '元素链接地址（a 标签默认采集）', '{"sdks":["Web"],"auto":true,"category":"Click"}', 0, 0),
  ('$element_type', '元素类型', 2, NULL, '控件/元素类型', '{"sdks":["Web","iOS","Android","MiniProgram"],"auto":true,"category":"Click"}', 0, 0),
  ('$event_duration', '事件时长', 1, '秒', '事件持续时间（秒），如 App 启动到退出、页面停留时长', '{"sdks":["iOS","Android","Web","MiniProgram"],"auto":true,"category":"Basic"}', 0, 1),
  ('$first_browser_charset', '首次浏览器字符类型', 2, NULL, '新用户首次访问时的浏览器字符集（SDK 1.8+）', '{"sdks":["Web"],"auto":true,"category":"UserProfile"}', 1, 0),
  ('$first_browser_language', '浏览器语言', 2, NULL, '新用户首次访问 SDK 页面时的浏览器语言', '{"sdks":["Web"],"auto":true,"category":"UserProfile"}', 1, 0),
  ('$first_channel_account_id', '首次渠道广告主 ID', 2, NULL, '首次渠道广告主 ID', '{"sdks":["iOS","Android"],"category":"Channel"}', 1, 0),
  ('$first_channel_ad_id', '首次渠道广告创意 ID', 2, NULL, '首次渠道广告创意 ID', '{"sdks":["iOS","Android"],"category":"Channel"}', 1, 0),
  ('$first_channel_adgroup_id', '首次渠道广告组 ID', 2, NULL, '首次渠道广告组 ID', '{"sdks":["iOS","Android"],"category":"Channel"}', 1, 0),
  ('$first_channel_campaign_id', '首次渠道广告计划 ID', 2, NULL, '首次渠道广告计划 ID', '{"sdks":["iOS","Android"],"category":"Channel"}', 1, 0),
  ('$first_channel_click_id', '首次渠道点击 ID', 2, NULL, '首次渠道点击 ID，用于与广告平台核对', '{"sdks":["iOS","Android"],"category":"Channel"}', 1, 0),
  ('$first_channel_keyword_id', '首次渠道关键词 ID', 2, NULL, '首次渠道关键词 ID', '{"sdks":["Web"],"category":"Channel"}', 1, 0),
  ('$first_channel_name', '首次渠道名称', 2, NULL, '首次渠道名称，关联投放数据', '{"sdks":["iOS","Android"],"category":"Channel"}', 1, 0),
  ('$first_referrer', '首次前向地址', 2, NULL, '新用户首次访问 SDK 页面时的前向地址', '{"sdks":["Web"],"auto":true,"category":"UserProfile","privacy":"Medium"}', 1, 0),
  ('$first_referrer_host', '首次前向域名', 2, NULL, '新用户首次访问 SDK 页面时的前向域名', '{"sdks":["Web"],"auto":true,"category":"UserProfile"}', 1, 0),
  ('$first_search_keyword', '首次搜索引擎关键词', 2, NULL, '新用户首次搜索引擎关键词（SDK 1.8+）', '{"sdks":["Web"],"auto":true,"category":"UserProfile"}', 1, 0),
  ('$first_traffic_source_type', '首次流量来源类型', 2, NULL, '新用户首次流量来源类型：付费广告/自然搜索/社交媒体/引荐/直接（SDK 1.8+）', '{"sdks":["Web"],"auto":true,"category":"UserProfile"}', 1, 0),
  ('$first_visit_time', '首次访问时间', 5, NULL, '新用户首次访问页面/启动 App 的时间', '{"sdks":["Web","iOS","Android"],"auto":true,"category":"UserProfile"}', 1, 0),
  ('$idmap_reason', 'ID 关联原因', 2, NULL, 'ID 关联的原因说明', '{"sdks":["Server"],"category":"Identity"}', 0, 0),
  ('$ios_install_disable_callback', '是否不进行追踪回调', 6, NULL, '是否禁用追踪回调', '{"sdks":["iOS"],"category":"Channel","privacy":"Low"}', 0, 0),
  ('$ios_install_source', 'App 渠道匹配所需要的设备指纹信息', 2, NULL, 'iOS IDFA 信息，服务端渠道匹配后删除', '{"sdks":["iOS"],"category":"Channel","privacy":"High","note":"不入库"}', 0, 0),
  ('$ip', 'IP', 2, NULL, '后端从 HTTP 请求解析的 IP 地址', '{"sdks":["iOS","Android","Web","MiniProgram","Server"],"source":"Nginx","auto":true,"category":"IP"}', 1, 0),
  ('$ip_isp', 'IP 运营商', 2, NULL, '由 IP 解析得到的运营商', '{"source":"IP","auto":true,"category":"IP"}', 1, 0),
  ('$is_channel_callback_event', '是否进行渠道匹配回调', 6, NULL, '事件的渠道匹配结果是否需要回调给渠道方', '{"sdks":["iOS","Android"],"category":"Channel","privacy":"Low"}', 0, 0),
  ('$is_deleted', '是否删除', 6, NULL, '记录是否有效', '{"category":"Item"}', 0, 0),
  ('$is_first_day', '是否首日访问', 6, NULL, '是否触发事件的第一天，服务端修正；可区分新老用户', '{"sdks":["iOS","Android","Web","MiniProgram"],"auto":true,"category":"Basic","privacy":"Low"}', 1, 0),
  ('$is_first_time', '是否首次触发事件', 6, NULL, '当前用户是否首次触发该事件，服务端二次修正', '{"sdks":["iOS","Android","Web","MiniProgram"],"auto":true,"category":"Basic","privacy":"Low"}', 1, 0),
  ('$is_login_id', '是否登录 ID', 6, NULL, '事件的 distinct_id 是否为登录 ID，数据入库时添加', '{"sdks":["iOS","Android","Web","MiniProgram","Server"],"auto":true,"category":"Identity","privacy":"Low"}', 1, 0),
  ('$is_valid', '是否封禁', 6, NULL, '记录是否有效', '{"category":"Item","privacy":"Low"}', 0, 0),
  ('$item_join', '物品匹配模式', 2, NULL, '用户维度表名，用于物品关联', '{"category":"Item"}', 0, 0),
  ('$kafka_offset', '$kafka_offset', 1, NULL, 'Kafka 消费偏移量', '{"source":"Server","category":"System"}', 0, 0),
  ('$latest_landing_page', '最近一次落地页', 2, NULL, '最近一次落地页 URL', '{"sdks":["Web"],"auto":true,"category":"Latest"}', 1, 0),
  ('$latest_referrer', '最近一次站外地址', 2, NULL, '最近一次站外前向地址（SDK 1.6+）', '{"sdks":["Web"],"auto":true,"category":"Latest","privacy":"Medium"}', 1, 0),
  ('$latest_referrer_host', '最近一次站外域名', 2, NULL, '最近一次站外域名（SDK 1.14.8+ 需手动开启）', '{"sdks":["Web"],"auto":false,"category":"Latest"}', 1, 0),
  ('$latest_sa_utm', '最近一次渠道来源', 2, NULL, '最近一次渠道来源参数', '{"sdks":["Web"],"category":"Latest"}', 1, 0),
  ('$latest_scene', '最近一次启动场景', 2, NULL, '最近一次小程序启动场景', '{"sdks":["MiniProgram"],"auto":true,"category":"Latest","privacy":"Low"}', 1, 0),
  ('$latest_search_keyword', '最近一次搜索引擎关键词', 2, NULL, '从 $latest_referrer 解析的搜索关键词（SDK 1.8+）', '{"sdks":["Web"],"auto":true,"category":"Latest"}', 1, 0),
  ('$latest_share_depth', '最近一次分享深度', 1, NULL, '最近一次分享链中的层级', '{"sdks":["MiniProgram"],"category":"Latest"}', 0, 1),
  ('$latest_share_distinct_id', '最近一次分享者', 2, NULL, '最近一次小程序分享者的用户 ID', '{"sdks":["MiniProgram"],"category":"Latest"}', 1, 0),
  ('$latest_share_method', '最近一次分享时途径', 2, NULL, '最近一次小程序分享途径（朋友圈/消息卡片等）', '{"sdks":["MiniProgram"],"auto":true,"category":"Latest","privacy":"Low"}', 1, 0),
  ('$latest_share_url_path', '最近一次分享路径', 2, NULL, '最近一次小程序分享时的页面路径', '{"sdks":["MiniProgram"],"category":"Latest"}', 1, 0),
  ('$latest_traffic_source_type', '最近一次流量来源类型', 2, NULL, '最近一次流量来源类型：付费广告/自然搜索/社交媒体/引荐/直接（SDK 1.8+）', '{"sdks":["Web"],"auto":true,"category":"Latest"}', 1, 0),
  ('$latest_utm_campaign', '最近一次广告系列名称', 2, NULL, '最近一次广告系列名称', '{"sdks":["Web"],"auto":true,"category":"Latest"}', 1, 0),
  ('$latest_utm_content', '最近一次广告系列内容', 2, NULL, '最近一次广告系列内容', '{"sdks":["Web"],"auto":true,"category":"Latest"}', 1, 0),
  ('$latest_utm_medium', '最近一次广告系列媒介', 2, NULL, '最近一次广告系列媒介', '{"sdks":["Web"],"auto":true,"category":"Latest"}', 1, 0),
  ('$latest_utm_source', '最近一次广告系列来源', 2, NULL, '最近一次广告系列来源', '{"sdks":["Web"],"auto":true,"category":"Latest"}', 1, 0),
  ('$latest_utm_term', '最近一次广告系列字词', 2, NULL, '最近一次广告系列关键字', '{"sdks":["Web"],"auto":true,"category":"Latest"}', 1, 0),
  ('$latitude', '纬度', 3, NULL, 'GPS 纬度，iOS/Android 需手动开启', '{"sdks":["iOS","Android"],"auto":false,"category":"Location","privacy":"High"}', 0, 1),
  ('$lib', 'SDK 类型', 2, NULL, 'SDK 类型，如 Android、iOS、js 等', '{"sdks":["iOS","Android","Web","MiniProgram","Server"],"auto":true,"category":"SDK"}', 1, 0),
  ('$lib_detail', '埋点细节', 2, NULL, '触发用户行为时的调用栈信息', '{"sdks":["iOS","Android","Web","MiniProgram"],"auto":true,"category":"SDK"}', 0, 0),
  ('$lib_method', '埋点方式', 2, NULL, '埋点触发方式（全埋点/代码埋点），Web/小程序统一为 code', '{"sdks":["iOS","Android","Web","MiniProgram"],"auto":true,"category":"SDK"}', 1, 0),
  ('$lib_plugin_version', 'SDK 插件版本号', 3, NULL, '神策分析插件版本号列表，如 ["android_plugin:4.2"]', '{"sdks":["iOS","Android"],"auto":true,"category":"SDK"}', 0, 0),
  ('$lib_version', 'SDK 版本', 2, NULL, 'SDK 版本号', '{"sdks":["iOS","Android","Web","MiniProgram","Server"],"auto":true,"category":"SDK"}', 1, 0),
  ('$location_info', '地理位置信息', 2, NULL, '地理位置信息', '{"category":"Location"}', 0, 0),
  ('$location_precision', '地理位置精度', 1, NULL, '地理位置精度', '{"category":"Location"}', 0, 0),
  ('$longitude', '经度', 3, NULL, 'GPS 经度，iOS/Android 需手动开启', '{"sdks":["iOS","Android"],"auto":false,"category":"Location","privacy":"High"}', 0, 1),
  ('$manufacturer', '设备制造商', 2, NULL, '设备制造商', '{"sdks":["iOS","Android","Web"],"auto":true,"source":"UA","category":"Device","privacy":"Medium"}', 1, 0),
  ('$map_scale', '地图缩放大小', 1, NULL, '地图缩放级别', '{"category":"Location"}', 0, 0),
  ('$matched_key', '渠道匹配关键字', 2, NULL, 'App 渠道匹配成功时的匹配字段（如 IMEI MD5、IP_UA），extractor 模块添加', '{"sdks":["iOS","Android"],"source":"Extractor","category":"Channel","privacy":"High"}', 0, 0),
  ('$matching_key_list', '渠道匹配关键字列表', 2, NULL, '激活事件所有匹配关键字列表（IMEI MD5/AndroidID/OAID/IP_UA 等），SA 1.14+', '{"sdks":["iOS","Android"],"source":"Extractor","category":"Channel","privacy":"High"}', 0, 0),
  ('$model', '设备型号', 2, NULL, '设备型号', '{"sdks":["iOS","Android","Web","MiniProgram"],"auto":true,"source":"UA","category":"Device","privacy":"Medium"}', 1, 0),
  ('$mp_bizmsgmenu_id', '公众号菜单会话选项', 2, NULL, '菜单会话消息选项 ID', '{"sdks":["Server"],"category":"WeChat"}', 0, 0),
  ('$mp_card_id', '公众号消息卡券 ID', 2, NULL, '公众号消息中的卡券 ID', '{"sdks":["Server"],"category":"WeChat"}', 0, 0),
  ('$mp_click_menu_type', '公众号菜单事件类型', 2, NULL, '公众号自定义菜单事件类型', '{"sdks":["Server"],"category":"WeChat"}', 1, 0),
  ('$mp_client_app_version', '小程序客户端版本', 2, NULL, '运行小程序的客户端应用版本', '{"sdks":["MiniProgram"],"auto":true,"category":"MiniGame"}', 1, 0),
  ('$mp_client_basic_library_version', '小程序基础库版本', 2, NULL, '小程序基础库版本', '{"sdks":["MiniProgram"],"auto":true,"category":"MiniGame"}', 1, 0),
  ('$mp_content', '公众号消息文本内容', 2, NULL, '公众号消息文本内容', '{"sdks":["Server"],"category":"WeChat"}', 0, 0),
  ('$mp_description', '公众号消息描述', 2, NULL, '公众号消息描述', '{"sdks":["Server"],"category":"WeChat"}', 0, 0),
  ('$mp_event_key', '公众号事件 KEY', 2, NULL, '公众号自定义菜单事件 KEY', '{"sdks":["Server"],"category":"WeChat"}', 0, 0),
  ('$mp_head_content', '公众号消息开头语', 2, NULL, '公众号消息开头语', '{"sdks":["Server"],"category":"WeChat"}', 0, 0),
  ('$mp_media_id', '公众号消息媒体 ID', 2, NULL, '公众号消息媒体 ID', '{"sdks":["Server"],"category":"WeChat"}', 0, 0),
  ('$mp_menu_id', '公众号菜单 ID', 2, NULL, '公众号菜单 ID', '{"sdks":["Server"],"category":"WeChat"}', 0, 0),
  ('$mp_msg_group_type', '公众号消息组消息类型', 3, NULL, '公众号消息组消息类型枚举', '{"sdks":["Server"],"category":"WeChat"}', 1, 0),
  ('$mp_msg_id', '公众号用户发送消息 ID', 2, NULL, '公众号用户发送消息 ID', '{"sdks":["Server"],"category":"WeChat"}', 0, 0),
  ('$mp_option_list', '公众号消息选项 ID', 3, NULL, '公众号消息选项 ID 列表', '{"sdks":["Server"],"category":"WeChat"}', 0, 0),
  ('$mp_pic_url', '公众号消息图片链接', 2, NULL, '公众号消息图片链接', '{"sdks":["Server"],"category":"WeChat"}', 0, 0),
  ('$mp_receive_msg_type', '公众号用户发送消息类型', 2, NULL, '公众号用户发送消息类型', '{"sdks":["Server"],"category":"WeChat"}', 1, 0),
  ('$mp_reply_appid', '回复的小程序 App ID', 2, NULL, '公众号回复的小程序 App ID', '{"sdks":["Server"],"category":"WeChat"}', 0, 0),
  ('$mp_send_msg_type', '公众号发送消息类型', 2, NULL, '公众号发送消息类型', '{"sdks":["Server"],"category":"WeChat"}', 1, 0),
  ('$mp_tail_content', '公众号消息结束语', 2, NULL, '公众号消息结束语', '{"sdks":["Server"],"category":"WeChat"}', 0, 0),
  ('$mp_thumb_media_id', '公众号消息缩略图媒体 ID', 2, NULL, '公众号消息缩略图媒体 ID', '{"sdks":["Server"],"category":"WeChat"}', 0, 0),
  ('$mp_title', '公众号消息标题', 2, NULL, '公众号消息标题', '{"sdks":["Server"],"category":"WeChat"}', 0, 0),
  ('$mp_url', '公众号消息链接', 2, NULL, '公众号消息链接', '{"sdks":["Server"],"category":"WeChat"}', 0, 0),
  ('$mp_voice_format', '公众号语音格式', 2, NULL, '公众号语音消息格式', '{"sdks":["Server"],"category":"WeChat"}', 0, 0),
  ('$mp_voice_recognition', '公众号消息语音识别结果', 2, NULL, '公众号语音消息识别文本', '{"sdks":["Server"],"category":"WeChat"}', 0, 0),
  ('$network_type', '网络类型', 2, NULL, '事件触发时的网络类型', '{"sdks":["iOS","Android","MiniProgram"],"auto":true,"category":"Device","privacy":"Low"}', 1, 0),
  ('$os', '操作系统', 2, NULL, '操作系统名称', '{"sdks":["iOS","Android","Web","MiniProgram"],"auto":true,"source":"UA","category":"Device","privacy":"Medium"}', 1, 0),
  ('$os_version', '操作系统版本', 2, NULL, '操作系统版本号', '{"sdks":["iOS","Android","Web","MiniProgram"],"auto":true,"source":"UA","category":"Device","privacy":"Medium"}', 1, 0),
  ('$page_height', '页面高度', 1, '像素', '页面总高度（像素），需集成 Page Height 插件', '{"sdks":["Web"],"auto":false,"category":"Web"}', 0, 1),
  ('$page_resource_size', '页面资源大小', 1, 'KB', '页面资源大小（KB），需 >0 且 <10GB，SDK 1.21.7+', '{"sdks":["Web"],"auto":true,"category":"Web"}', 0, 1),
  ('$page_x', '页面 X 坐标', 1, '像素', '点击距离页面左边距的位置（像素），SDK 1.21.5+', '{"sdks":["Web"],"auto":true,"category":"Click"}', 0, 0),
  ('$page_y', '页面 Y 坐标', 1, '像素', '点击距离页面顶部的位置（像素），SDK 1.21.5+', '{"sdks":["Web"],"auto":true,"category":"Click"}', 0, 0),
  ('$province', '省份', 2, NULL, '由 IP 解析得到', '{"sdks":["iOS","Android","Web","MiniProgram","Server"],"source":"IP","auto":true,"category":"IP","privacy":"Low"}', 1, 0),
  ('$receive_time', '$receive_time', 1, NULL, '服务器接收到事件的时间', '{"source":"Server","auto":true,"category":"System"}', 0, 0),
  ('$referrer', '前向地址', 2, NULL, '前一个页面的 URL；页面直接打开时为空字符串', '{"sdks":["Web","MiniProgram","iOS","Android"],"auto":true,"category":"Basic","privacy":"Medium"}', 1, 0),
  ('$referrer_host', '前向域名', 2, NULL, '$referrer 的 host 部分', '{"sdks":["Web"],"auto":true,"category":"Basic"}', 1, 0),
  ('$referrer_title', '前向页面标题', 2, NULL, '前一个页面的标题', '{"sdks":["Web"],"auto":true,"category":"Basic"}', 0, 0),
  ('$resume_from_background', '是否从后台唤醒', 6, NULL, 'App 是否从后台唤醒（$AppStart 事件属性）', '{"sdks":["iOS","Android"],"auto":true,"category":"Basic"}', 1, 0),
  ('$sa_utm', '渠道来源', 2, NULL, '渠道来源参数', '{"sdks":["Web"],"category":"Channel"}', 1, 0),
  ('$scene', '启动场景', 2, NULL, '小程序启动时的场景值', '{"sdks":["MiniProgram"],"auto":true,"category":"Basic","privacy":"Low"}', 1, 0),
  ('$screen_height', '屏幕高度', 1, '像素', '屏幕高度（iOS: 逻辑分辨率; Android: 物理像素）', '{"sdks":["iOS","Android","Web","MiniProgram"],"auto":true,"category":"Device","privacy":"Low"}', 1, 0),
  ('$screen_name', '页面名称', 2, NULL, 'Android: Activity/Fragment 包名和类名; iOS: ViewController 类名', '{"sdks":["iOS","Android"],"auto":true,"category":"Basic","privacy":"Low"}', 1, 0),
  ('$screen_orientation', '屏幕方向', 2, NULL, '设备当前方向（横屏/竖屏）', '{"sdks":["iOS","Android"],"auto":false,"category":"Device","privacy":"Low"}', 1, 0),
  ('$screen_width', '屏幕宽度', 1, '像素', '屏幕宽度（iOS: 逻辑分辨率; Android: 物理像素）', '{"sdks":["iOS","Android","Web","MiniProgram"],"auto":true,"category":"Device","privacy":"Low"}', 1, 0),
  ('$sf_audience_id', '运营受众 ID', 2, NULL, '运营受众 ID，仅存在受众规则时有值', '{"sdks":["Server"],"category":"Operation"}', 1, 0),
  ('$sf_channel_category', '消息通道类型', 2, NULL, '消息通道类型', '{"sdks":["Server"],"category":"Operation"}', 1, 0),
  ('$sf_channel_id', '运营计划推送通道 ID', 2, NULL, '运营计划推送通道 ID', '{"sdks":["Server"],"category":"Operation"}', 1, 0),
  ('$sf_channel_service_name', '消息发送服务商', 2, NULL, '消息发送服务商名称', '{"sdks":["Server"],"category":"Operation"}', 1, 0),
  ('$sf_close_type', '弹窗关闭按钮类型', 2, NULL, '弹窗关闭方式：遮罩层/右上角图标/底部图标/按钮', '{"sdks":["Web","App"],"category":"Operation"}', 0, 0),
  ('$sf_convert_id', '目标 ID', 2, NULL, '转化目标 ID', '{"sdks":["Server"],"category":"Operation"}', 0, 0),
  ('$sf_enter_plan_time', '进入计划时间', 5, NULL, '用户进入运营计划的时间', '{"sdks":["Server"],"category":"Operation"}', 0, 0),
  ('$sf_fail_reason', '消息发送失败原因', 2, NULL, '消息发送失败原因', '{"sdks":["Server"],"category":"Operation"}', 0, 0),
  ('$sf_keyword', '回复消息命中的关键词', 2, NULL, '公众号回复消息命中的关键词', '{"sdks":["Server"],"category":"Operation"}', 0, 0),
  ('$sf_keyword_rule_id', '关键词规则名称', 2, NULL, '关键词规则名称', '{"sdks":["Server"],"category":"Operation"}', 0, 0),
  ('$sf_lib_version', '弹窗 SDK 版本', 2, NULL, '弹窗 SDK 版本号', '{"sdks":["Web","App"],"category":"Operation"}', 0, 0),
  ('$sf_msg_element_action', '弹窗按钮行为', 2, NULL, '弹窗点击行为：URL 链接/自定义链接/关闭弹窗', '{"sdks":["Web","App"],"category":"Operation"}', 0, 0),
  ('$sf_msg_element_content', '弹窗按钮文案', 2, NULL, '弹窗按钮文案，仅按钮独有', '{"sdks":["Web","App"],"category":"Operation"}', 0, 0),
  ('$sf_msg_element_type', '弹窗按钮类型', 2, NULL, '弹窗元素类型：普通按钮/文字链接/图片链接/关闭图标/遮罩层', '{"sdks":["Web","App"],"category":"Operation"}', 1, 0),
  ('$sf_msg_errcode', '消息终态错误代码', 2, NULL, '消息终态错误代码', '{"sdks":["Server"],"category":"Operation"}', 0, 0),
  ('$sf_msg_group_id', '消息组 ID', 2, NULL, '消息组 ID', '{"sdks":["Server"],"category":"Operation"}', 0, 0),
  ('$sf_msg_group_type', '消息组消息类型枚举值', 3, NULL, '消息组中的消息类型枚举值', '{"sdks":["Server"],"category":"Operation"}', 1, 0),
  ('$sf_msg_id', '推送消息 ID', 2, NULL, '推送消息 ID', '{"sdks":["Server","Web","App"],"category":"Operation"}', 0, 0),
  ('$sf_msg_image_url', '弹窗图片 URL', 2, NULL, '弹窗图片的 CDN 存储地址', '{"sdks":["Web","App"],"category":"Operation"}', 0, 0),
  ('$sf_msg_status', '消息最终状态', 2, NULL, '消息最终状态', '{"sdks":["Server"],"category":"Operation"}', 1, 0),
  ('$sf_plan_id', '运营计划名称', 2, NULL, '实际上报为 ID，通过维度字典映射为计划名称', '{"sdks":["Server","Web","App"],"category":"Operation"}', 1, 0),
  ('$sf_plan_strategy_id', '实验组 ID', 2, NULL, '属性值 0 或 -1，0 代表实验组，-1 代表对照组', '{"sdks":["Server","Web","App"],"category":"Operation"}', 1, 0),
  ('$sf_plan_type', '计划类型', 2, NULL, '运营计划/流程画布/微信运营', '{"sdks":["Server","Web","App"],"category":"Operation"}', 1, 0),
  ('$sf_platform_tag', '平台类型标签', 2, NULL, '平台类型标签：ANDROID/IOS/H5/WEB', '{"sdks":["Web","App"],"category":"Operation"}', 1, 0),
  ('$sf_reply_contain_qr', '是否回复二维码', 6, NULL, '公众号回复消息是否包含二维码', '{"sdks":["Server"],"category":"Operation"}', 0, 0),
  ('$sf_strategy_unit_id', '策略器名称', 2, NULL, '运营策略器名称', '{"sdks":["Server"],"category":"Operation"}', 0, 0),
  ('$sf_succeed', '消息发送成功', 6, NULL, '消息是否发送成功（true/false）', '{"sdks":["Server","Web","App"],"category":"Operation"}', 0, 0),
  ('$sf_total_msgs', '配置的回复条数', 1, NULL, '配置的回复消息条数', '{"sdks":["Server"],"category":"Operation"}', 0, 1),
  ('$sf_total_msgs_success', '回复消息条数', 1, NULL, '实际成功回复的消息条数', '{"sdks":["Server"],"category":"Operation"}', 0, 1),
  ('$share_depth', '分享次数', 1, NULL, '分享链中的层级深度（原始访客 0，分享打开为 1，以此类推）', '{"sdks":["MiniProgram"],"auto":true,"category":"Basic"}', 0, 1),
  ('$share_distinct_id', '分享者', 2, NULL, '当前小程序分享者的用户 ID', '{"sdks":["MiniProgram"],"auto":true,"category":"Basic"}', 1, 0),
  ('$share_method', '分享时途径', 2, NULL, '分享途径：朋友圈分享/转发消息卡片等', '{"sdks":["MiniProgram"],"auto":true,"category":"Basic","privacy":"Low"}', 1, 0),
  ('$share_url_path', '分享路径', 2, NULL, '小程序分享时的页面路径', '{"sdks":["MiniProgram"],"auto":true,"category":"Basic","privacy":"Low"}', 1, 0),
  ('$short_url_key', '短链 Key', 2, NULL, '短链 URL 路径中最后一个节点值', '{"sdks":["iOS","Android","Web","MiniProgram"],"category":"Channel","privacy":"Low"}', 0, 0),
  ('$short_url_target', '短链目标地址', 2, NULL, '短链对应的完整目标 URL', '{"sdks":["iOS","Android","Web","MiniProgram"],"category":"Channel","privacy":"Low"}', 0, 0),
  ('$source_package_name', '来源应用包名', 2, NULL, '来源应用的包名', '{"sdks":["Android"],"auto":true,"category":"Basic","privacy":"Medium"}', 1, 0),
  ('$timezone_offset', '时区偏移量', 1, '分钟', '设备时区偏移量 × -1（分钟）', '{"sdks":["iOS","Android","Web","MiniProgram"],"auto":true,"category":"Basic","privacy":"Low"}', 1, 0),
  ('$title', '页面标题', 2, NULL, '页面标题；Android: Activity label; iOS: titleView; Web: document.title', '{"sdks":["iOS","Android","Web","MiniProgram"],"auto":true,"category":"Basic","privacy":"Low"}', 1, 0),
  ('$track_signup_original_id', '关联原始 ID', 2, NULL, '用户登录时关联匿名 ID，用于 ID 关联', '{"sdks":["iOS","Android","Web","MiniProgram","Server"],"auto":false,"category":"Identity","privacy":"High"}', 0, 0),
  ('$update_time', '更新时间', 1, NULL, '用户最近更新时间', '{"source":"Server","category":"System"}', 0, 0),
  ('$url', '页面地址', 2, NULL, '页面 URL；Android/iOS v3.2.8+: 同 $screen_name; Web: location.href', '{"sdks":["iOS","Android","Web","MiniProgram"],"auto":true,"category":"Basic","privacy":"Low"}', 1, 0),
  ('$url_host', '页面地址域名', 2, NULL, '服务端从 $url 解析的 host 部分', '{"sdks":["Web"],"source":"Server","auto":true,"category":"Basic"}', 1, 0),
  ('$url_path', '页面路径', 2, NULL, 'H5 页面 URL 中 "/" 到 "?" 之间的内容', '{"sdks":["Web","MiniProgram"],"auto":true,"category":"Basic","privacy":"Low"}', 1, 0),
  ('$url_query', '页面参数', 2, NULL, 'H5 页面 URL 中 "?" 之后的内容', '{"sdks":["Web","MiniProgram"],"auto":true,"category":"Basic","privacy":"Low"}', 0, 0),
  ('$user_agent', 'UserAgent', 2, NULL, '服务端解析的 UserAgent 字符串', '{"source":"Server","auto":true,"category":"Basic","privacy":"Medium"}', 0, 0),
  ('$utm_campaign', '广告系列名称', 2, NULL, '广告系列名称', '{"sdks":["iOS","Android","Web","MiniProgram"],"auto":false,"category":"Channel","privacy":"Medium"}', 1, 0),
  ('$utm_content', '广告系列内容', 2, NULL, '广告系列内容', '{"sdks":["iOS","Android","Web","MiniProgram"],"auto":false,"category":"Channel"}', 1, 0),
  ('$utm_matching_type', '渠道追踪匹配模式', 2, NULL, '渠道匹配模式：模糊匹配/精准匹配，extractor 模块添加', '{"sdks":["iOS","Android"],"source":"Extractor","category":"Channel","privacy":"Low"}', 1, 0),
  ('$utm_medium', '广告系列媒介', 2, NULL, '广告系列媒介', '{"sdks":["iOS","Android","Web","MiniProgram"],"auto":false,"category":"Channel"}', 1, 0),
  ('$utm_source', '广告系列来源', 2, NULL, '广告系列来源', '{"sdks":["iOS","Android","Web","MiniProgram"],"auto":false,"category":"Channel","privacy":"Medium"}', 1, 0),
  ('$utm_term', '广告系列字词', 2, NULL, '广告系列关键字', '{"sdks":["iOS","Android","Web","MiniProgram"],"auto":false,"category":"Channel"}', 1, 0),
  ('$viewport_height', '视区高度', 1, '像素', '浏览器可视区域实际高度（像素）', '{"sdks":["Web"],"auto":true,"category":"Web","privacy":"Low"}', 0, 1),
  ('$viewport_position', '视区距顶部的位置', 1, '像素', '当前滚动条距页面顶部的位置（像素）', '{"sdks":["Web"],"auto":true,"category":"Web"}', 0, 1),
  ('$viewport_width', '视区宽度', 1, '像素', '浏览器可视区域实际宽度（像素）', '{"sdks":["Web"],"auto":true,"category":"Web","privacy":"Low"}', 0, 1),
  ('$wifi', '是否 WIFI', 6, NULL, '事件触发时是否为 WIFI 网络', '{"sdks":["iOS","Android"],"auto":true,"category":"Device","privacy":"Low"}', 1, 0)
) AS t(name, cname, data_type, unit, comment, track_info, is_dimension, is_measure);



-- 初始化：创建默认项目（公共预置事件/属性通过 is_common=1 共享）
-- ============================================================
INSERT INTO track_project (name, cname, is_auto_create, status, create_time)
VALUES ('default', '默认项目', 1, 1, NOW());
